# Generated by Django 6.1 on 2026-08-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='gift_selections',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
