# Generated by Django 6.1 on 2026-08-16 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_gift_selections'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='parthen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyer',
            name='partner',
            field=models.ForeignKey(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_of', to='tickets.buyer'),
        ),
    ]
