# Generated by Django 6.1 on 2026-08-16 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_buyer_parthen_buyer_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='parthen',
        ),
    ]
