# Generated by Django 6.1 on 2026-08-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_buyer_parthen'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='parthen',
            field=models.BooleanField(default=False),
        ),
    ]
