# Generated by Django 6.1 on 2026-08-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_buyer_parthen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
